### ISSUE TITLE
关于package.json

### ISSUE THREAD

**Issue by bigwave-cl** [yanyixin/angular2-todolist#1]
请问package.json里面angular的相关包（例如:@angular/common这种类型的）你是在哪里查找的资料呢？能麻烦给个链接吗？有中文的当然更好，谢谢啦！

**Comment by yanyixin** [comment]
推荐看英文版官方的配置，我参考的就是官方的。
地址在这里：https://angular.io/docs/ts/latest/guide/webpack.html

**Comment by bigwave-cl** [comment]
非常感谢你的回复，我在上面找到了相关链接，谢谢，PS：我英文不行，不过我根据你的链接在中文资料里面找到了npm包的介绍，谢啦，非常感谢

**Comment by yanyixin** [comment]
不客气～ 有时中文官网的代码更新不及时，关于代码类的建议看英文官网。

**Comment by bigwave-cl** [comment]
谢谢你的建议，我会尝试去关注这方面的内容的，不过英语实在不行，只能靠翻译软件堵住了，衰

**Comment by bigwave-cl** [comment]
辅助

**Comment by yanyixin** [comment]
我也是呀，英语是硬伤，只能慢慢培养了

**Comment by bigwave-cl** [comment]
我感觉妹子英语都挺好的，你肯定是在骗我
